## Chapter2 Linear Algeba

## 2.1 Scalars, Vectors, Matrices and Tensors

In [1]:
import numpy as np

* __Scalars__: single number, $\textit s$
* __Vectors__: an array of numbers, $\textbf x$,fisrt element: $\textit x_1$. Point in space.
* __Matrics__: 2-D array of numbers, each element is identified by two indicies instead of just one. $\textbf A, \textbf A_{i,:},\textbf A_{:,i}, A_{m,n}$
* __Tensors__: array with more than two axes. $A_{i,j,k}$

Transpose: the transpose of a matrix is the mirror image of the matrix   across a diagonal line, caller the _main diagonal_.  
The tanspose of a vector is a matrix with only one row.  
Scalar is its own transpose

In [4]:
A = np.reshape(range(6),(2,3))
print('If matrix A is ')
print(A)
print('Transpose A is ')
AT=A.transpose()
print(AT)

print('Aij == (A^T)ji')
print(A[1,2]==AT[2,1])

If matrix A is 
[[0 1 2]
 [3 4 5]]
Transpose A is 
[[0 3]
 [1 4]
 [2 5]]
Aij == (A^T)ji
True


Add: add corresponding elements  
D = a · B + c where Di,j =a·Bi,j +c  

In [14]:
A = np.reshape(range(6),(2,3))
B = np.reshape(range(7,13),(2,3))
print(A)
print('+')
print(B)
print('is')
print(A+B)

[[0 1 2]
 [3 4 5]]
+
[[ 7  8  9]
 [10 11 12]]
is
[[ 7  9 11]
 [13 15 17]]


$C=A+b$  
The vector $b$ is added to each row of the matrix. This is called __broadcastring__

In [13]:
C = np.ones(3)
print(A)
print('+')
print(C)
print('is')
print(A+C)

[[0 1 2]
 [3 4 5]]
+
[ 1.  1.  1.]
is
[[ 1.  2.  3.]
 [ 4.  5.  6.]]


## 2.2 Multiplying Matrices and Vectors
The matrix product of matrices A and B is a third matrix C  
A must have the same number of columns as B has rows.  
If A is of shape m × n and B is of shape n × p, then C is of shape m × p.  
$\textbf {C = AB}$  
$C_{i,j}=\sum_{k}A_{i,k}B_{k,j}$ 

In [22]:
A = np.reshape(range(6),(2,3))
B = np.reshape(range(7,13),(3,2))
print(A)
print('multiply')
print(B)
print('is')
print(np.matmul(A,B))

[[0 1 2]
 [3 4 5]]
multiply
[[ 7  8]
 [ 9 10]
 [11 12]]
is
[[ 31  34]
 [112 124]]


__Element-wise product__ or __Hadamard product__, and is denoted as $\textbf A\odot \textbf B$

In [23]:
A = np.reshape(range(6),(2,3))
B = np.reshape(range(7,13),(2,3))
print(A)
print('hadamard multiply')
print(B)
print('is')
print(A*B)

[[0 1 2]
 [3 4 5]]
hadamard multiply
[[ 7  8  9]
 [10 11 12]]
is
[[ 0  8 18]
 [30 44 60]]


The __dot product__ between two vectors $x$ and $y$ of the same dimensionality is the matrix product $x^T y$.

In [26]:
A = np.array(range(6))
B = np.array(range(7,13))
print(A)
print('dot')
print(B)
print('is')
print(np.matmul(A.transpose(),B))
print('==')
print(np.dot(A,B))

[0 1 2 3 4 5]
dot
[ 7  8  9 10 11 12]
is
160
==
160


Distributive

In [28]:
A = np.reshape(range(6),(2,3))
B = np.reshape(range(7,13),(3,2))
C = np.reshape(range(13,19),(3,2))
print(np.matmul(A,B+C)==np.matmul(A,B)+np.matmul(A,C))

[[ True  True]
 [ True  True]]


Associative

In [31]:
A = np.reshape(range(6),(2,3))
B = np.reshape(range(7,13),(3,2))
C = np.reshape(range(13,19),(2,3))
print(np.matmul(A,np.matmul(B,C))==np.matmul(np.matmul(A,B),C))

[[ True  True  True]
 [ True  True  True]]


NO commutative

In [33]:
A = np.reshape(range(4),(2,2))
B = np.reshape(range(5,9),(2,2))
print(np.matmul(A,B)==np.matmul(B,A))

[[False False]
 [False False]]


The dot product between two
vectors is commutative:

In [34]:
A = np.array(range(4))
B = np.array(range(5,9))
print(np.dot(A,B)==np.dot(B,A))

True


The transpose of a matrix product has a simple form:
${(AB)^T=B^T A^T}$

In [38]:
A = np.reshape(range(6),(2,3))
B = np.reshape(range(7,13),(3,2))
print(np.matmul(A,B).transpose()==np.matmul(B.transpose(),A.transpose()))

[[ True  True]
 [ True  True]]


A system of linear equation in linear algebra:  
$$
\textbf {Ax=b}\\
\textbf A \in \mathbf{R}^{m*n}\\
\textbf x \in \mathbf{R}^{n}\\
$$
This is same as:  

$$
A_{1,1}x_1+A_{2,1}x_2+...+A_{1,n}x_n=b_1\\
...\\
A_{1,m}x_m+A_{2,m}x_m+...+A_{m,n}x_n=b_m
$$  
Matrix-vector product notation provides a more compact representation for equations of this form.

## 2.3 Identity and Inverse Matrices
* __identity matrix__: matrix that does not change any vector when we multiply that vector by that matrix. We denote the identity matrix that preserves n-dimensional vectors as $\textit I_n \in R^{n*n}$ and  
$ \forall \textbf x \in R^{n}, \textit I_n x = x$  
* __matrix inverse__: $\textbf A^{-1} \textbf A=\textbf I_n$  
So the equation above can solved by: $ \textbf x =\textbf A^{-1} \textbf b$



In [7]:
print(np.identity(5))
A = np.reshape(range(4),(2,2))
b = np.array([5,6])
print(np.matmul(np.linalg.inv(A),b))
print('OR')
print(np.linalg.solve(A,b))

[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
[-4.5  5. ]
OR
[-4.5  5. ]


When $A^{-1}$ exists, several different algorithms exist for finding it in closed form. In practice, $A^{-1}$ can be represented with only limited precision on a digital computer, algorithms that make use of the value $b$ can usually obtain more accurate estimates of $x$.

## 2.4 Linear Dependence and Span
